#!/bin/bash

export HOME=/app
for file in /app/.profile.d/*; do source $file; done
hash -r
cd /app
if [[ -f Procfile ]]; then
    bash -i $( ruby -e "require 'yaml';puts YAML.load_file('Procfile')['$1']" )
else
    bash -i $( ruby -e "require 'yaml';puts (YAML.load_file('.release')['default_process_types'] || {})['$1']")
fi
